version: '3.9'

networks:
  product-network:
    driver: bridge

services:

  db:
    container_name: "product-db-e2e"
    image: postgres:latest
    restart: always
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - product-network

  app:
    container_name: 'product-app-e2e'
    build:
      context: .
    depends_on:
        - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5454/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8444:8443"
    networks:
      - product-network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=8880
    ports:
      - "8880:8888"
    networks:
      - product-network